### PR TITLE
Upgrade reactive extensions to v3.

### LINKED ISSUE #16: Update to Rx 3.0
Provides dotnet core support.
Nugets have all change names....
e.g. Use System.Reactive instead of Rx-Main

### PR DESCRIPTION
**Pull request by karlatkinson**
Under new nuget package names.
v3 supports .net core.

Closes #16

### CODE REVIEW

**Comment by azdlowry** [comment]
The target framework is deliberately removed to allow the project to be built for both 4.5 and 4.6. I don't know if putting it back in will break this. 

Can you confirm that it builds correctly in both configurations?

**Comment by karlatkinson** [comment]
You only ever seem to target net45 references so not sure the net46 build is actually any different.
If you don't have the target framework, visual studio thinks the projects are targeting .net 4.0

If msbuild worked, not sure what else would break?
Think its easier to target different dependancy framework versions with project.json etc although I've yet to try this out.

**Comment by azdlowry** [comment]
The build command specifies the target framework.

**Comment by karlatkinson** [comment]
Try installing a nuget package that only supports .net 4.5+ on the master branch and you'll see what I mean.
And yep, I know it targets that, but the csproj references always use the net45 nuget folder locations.

**Comment by azdlowry** [comment]
Each configuration specifies the appropriate target framework so I think we are OK.

**Pull request merged**
